### ISSUE TITLE
Context Warnings

### ISSUE THREAD

**Issue by philogb** [dmnsgn/dgel#11]
Hi there! I am getting some warnings from Context.ts. None of it seems critical for the framework to work, but thought I'd raise it anyways so we can keep up with the WebGPU changes. Thank you for your amazing work!

`Calling getPreferredFormat() on a GPUCanvasContext is deprecated and will soon be removed. Call navigator.gpu.getPreferredCanvasFormat() instead, which no longer requires an adapter.`

`compositingAlphaMode is deprecated and will soon be removed. Please set alphaMode instead.`

`Setting an explicit size when calling configure() on a GPUCanvasContext has been deprecated, and will soon be removed. Please set the canvas width and height attributes instead. Note that after the initial call to configure() changes to the canvas width and height will now take effect without the need to call configure() again.`

**Comment by dmnsgn** [comment]
Thanks, fixed in 0.13.0 e2e562504e1d90f8e10bcc039e2fcc9f2ed09de0. I was trying to follow the latest deprecations here https://hackmd.io/@webgpu but it doesn't seem to be updated with the above.
