### ISSUE TITLE
Provide "@types/dgel"?

### ISSUE THREAD

**Issue by filonik** [dmnsgn/dgel#4]
Nice work, really looking forward to WebGPU!

Since the code is in TypeScript, I was wondering if there is any particular reason why the type declarations aren't also provided so that the library can be used from TypeScript?

[@types-dgel-0.2.1.zip](https://github.com/dmnsgn/dgel/files/5686163/%40types-dgel-0.2.1.zip)

**Comment by dmnsgn** [comment]
Thanks!

I have exported the declaration alongside the code in 0.3.0 so you should get autocomplete and can import them in typescript.
<img width="980" alt="Screenshot 2020-12-20 at 11 27 01" src="https://user-images.githubusercontent.com/1636460/102712099-4c81fb00-42b6-11eb-998c-bb09791a6d01.png">
