### ISSUE TITLE
context.resize should make use of devicePixelRatio

### ISSUE THREAD

**Issue by philogb** [dmnsgn/dgel#8]
Currently `context.resize` does not take into account a devicePixelRatio parameter. It would be great to add this as a feature (maybe sent as an option to the function) to get rid of aliasing effects.

**Comment by dmnsgn** [comment]
Thanks for the suggestion, added as a property to the context directly.

**Comment by philogb** [comment]
Beautiful thank you for being so responsive and for your work!
