### ISSUE TITLE
[[block]] attributes have been removed from WGSL

### ISSUE THREAD

**Issue by philogb** [dmnsgn/dgel#9]
I thought I'd report this warning I am getting in Chrome Canary 99.0.4765.0.

` warning: use of deprecated language feature: [[block]] attributes have been removed from WGSL
[[block]] struct CirclesUniform { `

Unfortunately I am still getting started here and not sure what the change should be.

**Comment by dmnsgn** [comment]
Thanks, that's from WGSL latest changes. Removed in 9.0.0.
